title: Xingchen Wang
email: xwang95@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Principal Developer - Building innovative solutions with clean, scalable code
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xingchen1224.github.io" # the base hostname & protocol for your site

# Site Settings
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
locale: "en-US"
title_separator: "-"
name: "Xingchen Wang"
repository: "Xingchen1224/xingchen1224.github.io"
# teaser: "/assets/images/teaser-default.jpg" # path of fallback teaser image (file missing)
# logo: "/assets/images/logo.png" # path of logo image to display in the masthead (file missing)
# og_image: "/assets/images/social-preview.jpg" # Open Graph default image (file missing)
masthead_title: " " # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs: true # true, false (default)
words_per_minute: 200

# SEO and Social
twitter:
  username: "xingchen1224"
facebook:
  username: "xingchen1224"
social:
  type: Person # Person or Organization (defaults to Person)
  name: Xingchen Wang # If the user or organization name differs from the site's name
  links:
    - "https://linkedin.com/in/xingchen-wang"
    - "https://github.com/Xingchen1224"

# Site Search
search: true
search_full_content: true
search_provider: lunr
lunr:
  search_within_pages: true

# Analytics
analytics:
  provider: false # false (default), "google", "google-universal", "google-gtag", "custom"
  plausible:
    domain: # "yourdomain.com"
    # Optional: specify Plausible server if self-hosted
    # src: "https://your-plausible-server.com/js/plausible.js"

# Comments
comments:
  provider: false # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
  giscus:
    repo_id: # Repo ID from https://giscus.app
    category_name: # Discussion category name  
    category_id: # Category ID from https://giscus.app
    discussion_term: # "pathname" (default), "url", "title", "og:title"
    reactions_enabled: # "1" (default), "0"
    theme: # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - any_additional_item # any user-defined listing goes here

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

# Archives - Removed
# category_archive:
#   type: liquid
#   path: /categories/
# tag_archive:
#   type: liquid
#   path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

author:
  name   : "Xingchen Wang"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Principal Developer passionate about clean code, scalable systems, and innovative solutions."
  location: "Global"
  email: "xwang95@outlook.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:xwang95@outlook.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/xingchen-wang"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Xingchen1224"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      toc: true
      toc_label: "Contents"
      toc_icon: "cog"
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false
      share: true
      comments: false
      sidebar:
        nav: "projects"

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Xingchen1224"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/xingchen-wang"
